# Generated by Django 3.1.5 on 2021-01-30 14:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MythicDifficult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Уровень сложности')),
                ('description', models.TextField(verbose_name='Описание')),
                ('priceInDollars', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в долларах')),
                ('priceInEuro', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в евро')),
            ],
        ),
        migrations.CreateModel(
            name='MythicOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Опция')),
                ('priceInDollars', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в долларах')),
                ('priceInEuro', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в евро')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование активности')),
                ('difficult', models.CharField(max_length=100, verbose_name='Сложность')),
                ('priceInDollars', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в долларах')),
                ('priceInEuro', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в евро')),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=10), size=10)),
            ],
        ),
    ]
